Repository ember-cli/ember-addon-blueprint, pull requests merged in 2025-09, with the labels that each got.

#77 Remove unnecessary backticks in `.try.mjs` file
  files/.try.mjs
Labels: bug

#78 Remove root `package-lock.json` file
  package-lock.json
Labels: bug

#80 Sort `devDependencies` in generated `package.json` file
  files/package.json
Labels: bug

#86 Update to stable Glint
  files/package.json
  files/rollup.config.mjs
  files/tsconfig.json
  files/tsconfig.publish.json
Labels: enhancement

#81 Update Ember version in compat section in generated README file
  files/README.md
Labels: documentation
